# Build website
[build]
  command = ""
  publish = ""

[[redirects]]
  from = "/"
  to = "https://www.pixelastic.com/projects/"
  force = true
  status = 301

# Open-Source documentation
[[redirects]]
  from = "/firost/*"
  to = "https://pixelastic-firost.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/golgoth/*"
  to = "https://pixelastic-golgoth.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/norska/*"
  to = "https://pixelastic-norska.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/on-circle/*"
  to = "https://pixelastic-on-circle.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/aoinan/*"
  to = "https://pixelastic-aoinan.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/imoen/*"
  to = "https://pixelastic-imoen.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/reddinx/*"
  to = "https://pixelastic-reddinx.netlify.app/:splat"
  status = 200

# Fun websites
[[redirects]]
  from = "/magic/*"
  to = "https://pixelastic-magic.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/dark/*"
  to = "https://pixelastic-dark.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/landscapes/*"
  to = "https://pixelastic-landscapes.netlify.app/:splat"
  status = 200

# This project is deprecated and now part of Norska
[[redirects]]
  from = "/tailwind-config-norska/*"
  to = "https://projects.pixelastic.com/norska/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
