# Build website
[build]
  command = ""
  publish = ""

[[redirects]]
  from = "/"
  to = "https://www.pixelastic.com/projects/"
  force = true
  status = 301

[[redirects]]
  from = "/tailwind-config-norska/*"
  to = "https://pixelastic-tailwind-config-norska.netlify.app/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
